[package]
name = "rocket"
version = "0.2.0"
edition = "2021"

[dependencies]
octoapp = { path = "../octoapp", features = ["rocket"] }
tokio = { version = "1", features = ["full"] }
rocket = { version = "0.5" }
