name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-build.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo.yml@main
    secrets: inherit
    permissions:
      contents: read
      security-events: write
    with:
      # TODO: We might want to run these in the future
      examples: "false"
